src/Clients/Web/PhoneBook.Web.WebApp/Models/BookContactType.cs
using System.Drawing;

namespace PhoneBook.Web.WebApp.Models
{
    public class DropDownListForItemModel
    {
        public int Id { get; set; }
        public string Text { get; set; }
    }

}

src/Clients/Web/PhoneBook.Web.WebApp/Models/ErrorViewModel.cs
namespace PhoneBook.Web.WebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/Clients/Web/PhoneBook.Web.WebApp/Controllers/BookContactController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using PhoneBook.Web.Business.Abstract;
using PhoneBook.Web.Core;
using PhoneBook.Web.Core.Enum;
using PhoneBook.Web.Entities.Dto.Book;
using PhoneBook.Web.Entities.Dto.BookContact;
using PhoneBook.Web.WebApp.Infrastructures.Helper;
using System;

namespace PhoneBook.Web.WebApp.Controllers
{
    public class BookContactController : Controller
    {

        private readonly ILogger<BookContactController> _logger;
        private readonly IBookService _bookService;
        private readonly IBookContactService _bookContactService;
        private readonly IMapper _mapper;
        public BookContactController(ILogger<BookContactController> logger, IBookService bookService, IBookContactService bookContactService, IMapper mapper)
        {
            _logger = logger;
            _bookService = bookService;
            _bookContactService = bookContactService;
            _mapper = mapper;
        }

        public IActionResult Index(Guid bookUuid)
        {
            var book = _bookService.GetById(bookUuid);
            return View(book.Data);
        }

        public IActionResult GetListByBook(Guid bookUuid)
        {
            var controlData = _bookContactService.GetListByBook(bookUuid);

            if (controlData.IsSuccessful)
            {
                return Json(controlData);
            }
            else
            {
                return Json(Response<BookContactDto>.Fail(Enums.ResponseStatusEnum.Success.GetEnumInteger(), new List<string> { "Not Found" }));
            }
        }

        public ActionResult InsertModal(Guid bookUUID)
        {
            var model = new InsertBookContactDto() { BookUUID = bookUUID };
            return Json(Response<string>.Success(this.RenderViewToString("Insert", model), Enums.ResponseStatusEnum.Success.GetEnumInteger()));
        }

        public ActionResult Insert(InsertBookContactDto model)
        {
            var response = _bookContactService.Insert(model);
            return Json(response);
        }

        public ActionResult EditModal(Guid uuid)
        {
            var controlData = _bookContactService.GetById(uuid);

            if (controlData.IsSuccessful)
            {
                var model = _mapper.Map<UpdateBookContactDto>(controlData.Data);
                return Json(Response<string>.Success(this.RenderViewToString("Edit", model), Enums.ResponseStatusEnum.Success.GetEnumInteger()));
            }
            else
            {
                return Json(Response<string>.Fail(Enums.ResponseStatusEnum.Success.GetEnumInteger(), new List<string> { "Not Found" }));
            }
        }

        public ActionResult Edit(UpdateBookContactDto model)
        {
            var response = _bookContactService.Update(model);
            return Json(response);
        }

        public ActionResult GetBookContacts()
        {
            var response = _bookContactService.GetBookContacts();
            return Json(response);
        }

        public ActionResult Delete(Guid uuid)
        {
            var response = _bookContactService.Delete(uuid);
            return Json(response);
        }

    }
}

src/Clients/Web/PhoneBook.Web.WebApp/Controllers/BookController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using PhoneBook.Web.Business.Abstract;
using PhoneBook.Web.Core;
using PhoneBook.Web.Core.Enum;
using PhoneBook.Web.Entities.Dto.Book;
using PhoneBook.Web.WebApp.Infrastructures.Helper;
using System;

namespace PhoneBook.Web.WebApp.Controllers
{
    public class BookController : Controller
    {

        private readonly ILogger<BookController> _logger;
        private readonly IBookService _bookService;
        private readonly IMapper _mapper;
        public BookController(ILogger<BookController> logger, IBookService bookService, IMapper mapper)
        {
            _logger = logger;
            _bookService = bookService;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Detail(Guid bookUuid)
        {
            var result = _bookService.GetBookIncludeContact(bookUuid);
            return View(result);
        }

        public ActionResult InsertModal()
        {
            var model = new InsertBookDto();
            return Json(Response<string>.Success(this.RenderViewToString("Insert", model), Enums.ResponseStatusEnum.Success.GetEnumInteger()));
        }

        public ActionResult Insert(InsertBookDto model)
        {
            var response = _bookService.Insert(model);
            return Json(response);
        }

        public ActionResult EditModal(Guid uuid)
        {
            var controlData = _bookService.GetById(uuid);

            if (controlData.IsSuccessful)
            {
                var model = _mapper.Map<UpdateBookDto>(controlData.Data);
                return Json(Response<string>.Success(this.RenderViewToString("Edit", model), Enums.ResponseStatusEnum.Success.GetEnumInteger()));
            }
            else
            {
                return Json(Response<string>.Fail(Enums.ResponseStatusEnum.Success.GetEnumInteger(), new List<string> { "Not Found" }));
            }
        }

        public ActionResult Edit(UpdateBookDto model)
        {
            var response = _bookService.Update(model);
            return Json(response);
        }

        public ActionResult GetBooks()
        {
            var response = _bookService.GetBooks();
            return Json(response);
        }

        public ActionResult Delete(Guid uuid)
        {
            var response = _bookService.Delete(uuid);
            return Json(response);
        }

    }
}

src/Clients/Web/PhoneBook.Web.WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PhoneBook.Web.Business.Abstract;
using PhoneBook.Web.WebApp.Models;
using System.Diagnostics;

namespace PhoneBook.Web.WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IBookService _bookService;
        public HomeController(ILogger<HomeController> logger, IBookService bookService)
        {
            _logger = logger;
            _bookService = bookService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Clients/Web/PhoneBook.Web.WebApp/Controllers/ReportController.cs
using Microsoft.AspNetCore.Mvc;
using PhoneBook.Web.Business.Abstract;
using PhoneBook.Web.Core;
using PhoneBook.Web.Core.Enum;
using PhoneBook.Web.Entities.Dto.Report;
using PhoneBook.Web.WebApp.Infrastructures.Helper;

namespace PhoneBook.Web.WebApp.Controllers
{
    public class ReportController : Controller
    {

        private readonly IReportService _reportService;

        public ReportController(IReportService reportService)
        {
            _reportService = reportService;
        }

        public IActionResult Index()
        {
           var model =  _reportService.GetReports();
            return View(model);
        }

        public IActionResult GetReports()
        {
            var model = _reportService.GetReports();
            return Json(model);
        }

        public IActionResult CreateReportModal()
        {
            var model = new ReportRequestDto();
            return Json(Response<string>.Success(this.RenderViewToString("CreateReportRequest", model), Enums.ResponseStatusEnum.Success.GetEnumInteger()));
        }

        public IActionResult CreateReportRequest(ReportRequestDto model)
        {
            var response = _reportService.CreateReportRequest(model);
            return Json(response);
        }

        public IActionResult Detail(Guid uuid)
        {
            var response = _reportService.GetById(uuid);
            return View(response);
        }
    }
}

src/Clients/Web/PhoneBook.Web.WebApp/Views/Book/Detail.cshtml
@model PhoneBook.Web.Core.Response<PhoneBook.Web.Entities.Dto.Book.BookDto>
@using PhoneBook.Web.Core.Enum
@{
    List<DropDownListForItemModel> BookContactTypes = new List<DropDownListForItemModel> {
        new DropDownListForItemModel {
            Id = 0,
            Text = "Phone"
        },
        new DropDownListForItemModel {
             Id = 1,
            Text = "Email"
        },
        new DropDownListForItemModel {
             Id = 2,
            Text = "Location"
        }
    };
}

<div class="text-center">
    @if (Model.IsSuccessful)
    {
        <h5>@Model.Data.Name @Model.Data.LastName Details</h5>

        <br />

        <h6><b>UUID :</b> @Model.Data.UUID</h6>
        <h6><b>Name :</b> @Model.Data.Name</h6>
        <h6><b>LastName :</b> @Model.Data.LastName</h6>
        <h6><b>Company :</b> @Model.Data.Company</h6>

        <hr />

        <h5>Contacts</h5>

        <hr />

        @foreach (var item in Model.Data.BookContacts)
        {
            <h6><b>UUID :</b> @item.UUID</h6>
            <h6><b>Type :</b> @BookContactTypes[item.Type.GetEnumInteger()].Text</h6>
            <h6><b>Information :</b> @item.Information</h6>

            <hr />
        }
    }


</div>

src/Clients/Web/PhoneBook.Web.WebApp/Views/Book/Edit.cshtml
@model PhoneBook.Web.Entities.Dto.Book.UpdateBookDto
@using PhoneBook.Web.Core.Enum
@{
    Layout = null;
}

<div class="modal-body px-sm-5 pt-50">
    <section class="vertical-wizard">
        <div class="bs-stepper vertical vertical-wizard-example p-4">
            <form id="CreateForm" >
                @Html.HiddenFor(i => i.UUID)
                <div class="row">
                    <div class="mb-1">
                        <div class="col-12">
                            <label class="form-label" for="Name">Name</label>
                            @Html.TextBoxFor(i => i.Name, new { @class = "form-control", @autocomplete = "off", @placeholder = "Name" })
                        </div>
                    </div>

                    <div class="mb-1">
                        <div class="col-12">
                            <label class="form-label" for="Description">Lastname</label>
                            @Html.TextBoxFor(i => i.LastName, new { @class = "form-control", @autocomplete = "off", @placeholder = "LastName" })
                        </div>
                    </div>

                    <div class="mb-1">
                        <div class="col-12">
                            <label class="form-label" for="State">Company</label>
                            @Html.TextBoxFor(i => i.Company, new { @class = "form-control", @autocomplete = "off", @placeholder = "Company" })
                        </div>
                    </div>

                    <div class="col-12 text-center mt-2 pt-50">
                        <button type="reset" class="btn btn-outline-secondary me-1" data-bs-dismiss="modal" aria-label="Close">
                            Close
                        </button>
                        <button id="submit" type="submit" id="btn-save-role" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </section>
</div>


<script>
    $('#submit').on('click', function(){
        $.ajax({
            async: false,
            type: "post",
            dataType: "json",
            data: $("#CreateForm").serialize(),
            url: '/Book/Edit',
            success: function (result) {
                if (response.StatusCode == '@(Enums.ResponseStatusEnum.Success.GetEnumInteger())') {
                }
                else {
                }
            },
            error: function () {
            },
            beforeSend: function () {
            },
            complete: function () {
                document.location.href = "/Home/Index";
            }
        });
    });

</script>

src/Clients/Web/PhoneBook.Web.WebApp/Views/Book/Insert.cshtml
@model PhoneBook.Web.Entities.Dto.Book.InsertBookDto
@using PhoneBook.Web.Core.Enum
@{
    Layout = null;
}

<div class="modal-body px-sm-5 pt-50">
    <section class="vertical-wizard">
        <div class="bs-stepper vertical vertical-wizard-example p-4">
            <form id="CreateForm">
                <div class="row">
                    <div class="mb-1">
                        <div class="col-12">
                            <label class="form-label" for="Name">Name</label>
                            @Html.TextBoxFor(i => i.Name, new { @class = "form-control", @autocomplete = "off", @placeholder = "Name" })
                        </div>
                    </div>

                    <div class="mb-1">
                        <div class="col-12">
                            <label class="form-label" for="Description">Lastname</label>
                            @Html.TextBoxFor(i => i.LastName, new { @class = "form-control", @autocomplete = "off", @placeholder = "LastName" })
                        </div>
                    </div>

                    <div class="mb-1">
                        <div class="col-12">
                            <label class="form-label" for="State">Company</label>
                            @Html.TextBoxFor(i => i.Company, new { @class = "form-control", @autocomplete = "off", @placeholder = "Company" })
                        </div>
                    </div>

                    <div class="col-12 text-center mt-2 pt-50">
                        <button type="reset" class="btn btn-outline-secondary me-1" data-bs-dismiss="modal" aria-label="Close">
                            Close
                        </button>
                        <button id="submit" type="submit" id="btn-save-role" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </section>
</div>


<script>
    $('#submit').on('click', function () {
        $.ajax({
            async: false,
            type: "post",
            dataType: "json",
            data: $("#CreateForm").serialize(),
            url: '/Book/Insert',
            success: function (result) {
                if (response.StatusCode == '@(Enums.ResponseStatusEnum.Success.GetEnumInteger())') {
                }
                else {
                }
            },
            error: function () {
            },
            beforeSend: function () {
            },
            complete: function () {
                document.location.href = "/Home/Index";
            }
        });
    });

</script>

src/Clients/Web/PhoneBook.Web.WebApp/Views/BookContact/Index.cshtml
@model PhoneBook.Web.Entities.Dto.Book.BookDto
@using PhoneBook.Web.Core.Enum
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h5 id="title">@Model.Name @(Model.LastName)'s Contacts</h5>
    <table class="table table-bordered" id="bookContactTable">
        <thead>
            <tr>
                <th scope="col">UUID</th>
                <th scope="col">BookUUID</th>
                <th scope="col">Type</th>
                <th scope="col">Information</th>
                <th scope="col"><button type="button" onclick="InsertBookContact()" class=" btn btn-success">Add</button></th>
            </tr>
        </thead>
        <tbody id="bookContactBody">
        </tbody>
    </table>
</div>

<script>

    LoadBookTable();

    function LoadBookTable() {
        $('#bookContactBody').html('');
        $.ajax({
            url: '@Url.Action("GetListByBook","BookContact")',
            type: 'POST',
            dataType: 'json',
            data: { bookUuid: '@Model.UUID' },
            success: function (response) {
                if (response.StatusCode == '@(Enums.ResponseStatusEnum.Success.GetEnumInteger())' && response.Data.length > 0) {
                    console.log(response.Data);
                    response.Data.forEach((item) => {
                        let innerHtml =
                            '<tr>' +
                            '<th>' + item.UUID + '</th>' +
                            '<td>' + item.BookUUID + '</td>' +
                            '<td>' + (item.Type == '@(Enums.ContactTypeEnum.Email.GetEnumInteger())' ? "Email" : item.Type == '@(Enums.ContactTypeEnum.Phone.GetEnumInteger())' ? "Phone" : "Location") + '</td>' +
                            '<td>' + item.Information + '</td>' +
                            `<td><button onclick="EditBookContact('` + item.UUID + `')" type="button" class="btn btn-primary">Edit</button>` +
                            `<button onclick="DeleteBookContact('` + item.UUID + `')" type="button" class="btn btn-danger">Delete</button>` +
                            `</td>` +
                            '</tr>';
                        $('#bookContactBody').append(innerHtml);
                    });
                }
            },
            error: function (hata) {

            }
        });
    }

</script>


<script>

    function InsertBookContact(uuid) {
        $.ajax({
            url: '@Url.Action("InsertModal","BookContact")',
            type: 'POST',
            dataType: 'json',
            data: { bookUuid: '@Model.UUID' },
            success: function (response) {
                if (response.StatusCode == '@(Enums.ResponseStatusEnum.Success.GetEnumInteger())') {
                    console.log(response)
                    console.log(response.Data)
                    ShowBootbox('Insert', 'fa-solid fa-pen-to-square',
                        response.Data,
                        [],
                        'large',
                        'modal-primary',
                        'false'
                    );
                }
            },
            error: function (hata) {

            }
        });
    }

    function EditBookContact(uuid) {
        $.ajax({
            url: '@Url.Action("EditModal","BookContact")',
            type: 'POST',
            dataType: 'json',
            data: { uuid: uuid },
            success: function (response) {
                if (response.StatusCode == '@(Enums.ResponseStatusEnum.Success.GetEnumInteger())') {
                    ShowBootbox('Edit', 'fa-solid fa-pen-to-square',
                        response.Data,
                        [],
                        'large',
                        'modal-primary',
                        'false'
                    );
                }
                else{
                    $('#bookBody').append(response.Errors[0]);
                }
            },
            error: function (hata) {

            }
        });
    }

    function DeleteBookContact(uuid) {
        $.ajax({
            url: '@Url.Action("Delete","BookContact")',
            type: 'POST',
            dataType: 'json',
            data: { uuid: uuid },
            success: function (response) {
                if (response.StatusCode == '@(Enums.ResponseStatusEnum.Success.GetEnumInteger())') {
                    LoadBookTable();
                }
            },
            error: function (hata) {

            }
        });
    }

</script>

src/Clients/Web/PhoneBook.Web.WebApp/Views/BookContact/ShowModal.cshtml
@model IEnumerable<PhoneBook.Web.Entities.Dto.BookContact.BookContactDto>
@using PhoneBook.Web.Core.Enum
@{
    Layout = null;
}

<div class="text-center">
    <table class="table table-bordered" id="bookContactTable">
        <thead>
            <tr>
                <th scope="col">UUID</th>
                <th scope="col">Type</th>
                <th scope="col">Information</th>
                <th scope="col"><button type="button" onclick="InsertBookContact()" class=" btn btn-success">Add</button></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.UUID</td>
                    <td>@item.Type</td>
                    <td>@item.Information</td>
                </tr>
            }
        </tbody>
    </table>
</div>

<script>

    function InsertBookContact(uuid) {
        $.ajax({
            url: '@Url.Action("InsertModal","BookContact")',
            type: 'POST',
            success: function (response) {
                if (response.StatusCode == '@(Enums.ResponseStatusEnum.Success.GetEnumInteger())') {
                    console.log(response)
                    console.log(response.Data)
                    ShowBootbox('Insert', 'fa-solid fa-pen-to-square',
                        response.Data,
                        [],
                        'large',
                        'modal-primary',
                        'false'
                    );
                }
            },
            error: function (hata) {

            }
        });
    }

    function EditBookContact(uuid) {
        $.ajax({
            url: '@Url.Action("EditModal","BookContact")',
            type: 'POST',
            dataType: 'json',
            data: { uuid: uuid },
            success: function (response) {
                if (response.StatusCode == '@(Enums.ResponseStatusEnum.Success.GetEnumInteger())') {
                    ShowBootbox('Edit', 'fa-solid fa-pen-to-square',
                        response.Data,
                        [],
                        'large',
                        'modal-primary',
                        'false'
                    );
                }
            },
            error: function (hata) {

            }
        });
    }

    function DeleteBookContact(uuid) {
        $.ajax({
            url: '@Url.Action("Delete","BookContact")',
            type: 'POST',
            dataType: 'json',
            data: { uuid: uuid },
            success: function (response) {
                if (response.StatusCode == '@(Enums.ResponseStatusEnum.Success.GetEnumInteger())') {
                    LoadBookTable();
                }
            },
            error: function (hata) {

            }
        });
    }
</script>

src/Clients/Web/PhoneBook.Web.WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/Clients/Web/PhoneBook.Web.WebApp/Views/Report/Index.cshtml
@model PhoneBook.Web.Core.Response<List<PhoneBook.Web.Entities.Dto.Report.ReportDto>>

@using PhoneBook.Web.Core.Enum
@{
    ViewData["Title"] = "Reports";
}

<div class="text-center">
    <h5>Reports</h5>
    <table class="table table-bordered" id="reportTable">
        <thead>
            <tr>
                <th scope="col">UUID</th>
                <th scope="col">RequestUUID</th>
                <th scope="col">Request Date</th>
                <th scope="col">Status</th>
                <th scope="col">Location</th>
                <th scope="col">Person Count By Location</th>
                <th scope="col">Person Phone Count By Location</th>
                <th scope="col">Actions</th>
                <th scope="col"><button type="button" onclick="Refresh()" class=" btn btn-success">Refresh</button><button onclick="CreateReport()" type="button" class="btn btn-info">Create</button></th>
            </tr>
        </thead>
        <tbody id="reportTableBody">
            @if (Model.IsSuccessful)
            {
                foreach (var item in Model.Data)
                {
                    <tr>
                        <td>@item.UUID</td>
                        <td>@item.RequestUUID</td>
                        <td>@item.RequestDate</td>
                        <td>@item.Status</td>
                        <td>@item.Location</td>
                        <td>@item.PersonCount</td>
                        <td>@item.PersonPhoneCount</td>
                        <td><a href="/Report/Detail?uuid=@item.UUID" type="button" class="btn btn-info">Detail</a></td>
                        <td></td>
                    </tr>
                }
            }

        </tbody>
    </table>
</div>

<script>

    function Refresh() {
        $('#reportTableBody').html('');
        $.ajax({
            url: '@Url.Action("GetReports","Report")',
            type: 'POST',
            dataType: 'json',
            success: function (response) {
                if (response.StatusCode == '@(Enums.ResponseStatusEnum.Success.GetEnumInteger())' && response.Data.length > 0) {
                    console.log(response.Data);
                    response.Data.forEach((item) => {
                        let innerHtml =
                            '<tr>' +
                            '<td>' + item.UUID + '</td>' +
                            '<td>' + item.RequestUUID + '</td>' +
                            '<td>' + item.RequestDate + '</td>' +
                            '<td>' + (item.Status == '@(Enums.ReportStatusEnum.Completed.GetEnumInteger())' ? "Completed" : "Processing") + '</td>' +
                            '<td>' + item.Location + '</td>' +
                            '<td>' + item.PersonCount + '</td>' +
                            '<td>' + item.PersonPhoneCount + '</td>' +
                            `<td>` +
                            `<a href="/Report/Detail?uuid=` + item.UUID + `" type="button" class="btn btn-success">Detail</a>` +
                            `</td>` +
                            '</tr>';
                        $('#reportTableBody').append(innerHtml);
                    });
                }
            },
            error: function (hata) {

            }
        });
    }

</script>


<script>

    function DetailReport(uuid) {
        $.ajax({
            url: '@Url.Action("Detail","Report")',
            type: 'POST',
            dataType: 'json',
            data: { uuid: uuid },
            success: function (response) {
                if (response.StatusCode == '@(Enums.ResponseStatusEnum.Success.GetEnumInteger())') {
                    ShowBootbox('Detail', 'fa-solid fa-pen-to-square',
                        response.Data,
                        [],
                        'large',
                        'modal-primary',
                        'false'
                    );
                }
                else {
                    $('#bookBody').append(response.Errors[0]);
                }
            },
            error: function (hata) {

            }
        });
    }

     function CreateReport() {
        $.ajax({
            url: '@Url.Action("CreateReportModal","Report")',
            type: 'POST',
            dataType: 'json',
            success: function (response) {
                if (response.StatusCode == '@(Enums.ResponseStatusEnum.Success.GetEnumInteger())') {
                    ShowBootbox('Create Report Request', 'fa-solid fa-pen-to-square',
                        response.Data,
                        [],
                        'large',
                        'modal-primary',
                        'false'
                    );
                }
                else {
                    $('#bookBody').append(response.Errors[0]);
                }
            },
            error: function (hata) {

            }
        });
    }

</script>

src/Clients/Web/PhoneBook.Web.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PhoneBook.Web.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PhoneBook.Web.WebApp.styles.css" asp-append-version="true" />


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PhoneBook.Web.WebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Report" asp-action="Index">Reports</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PhoneBook.Web.WebApp - <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/bootbox/bootbox.js"></script>
    <script>
        function ShowBootbox(title, titleIcon, content, buttons, size, type, bdcontrol) {
            bootbox.dialog({
                titleIcon,
                backdrop: bdcontrol,
                title: title,
                size: size,
                buttons: buttons,
                className: type, //'modal-primary',
                message: content,
                animate: true,
                //onEscape: function () {

                //},
                callback: function() {
                }
            });
        }

         function HideBootbox() {
            $(".modal").closest('.modal').modal('hide');
        }
    </script>


    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>